### ISSUE TITLE
Chrome extension can't find article ID

### ISSUE THREAD

**Issue by justinyoo** [toddanglin/PublishToDev#4]
Hi, Todd.

I found that the preview page has recently updated so the existing logic is no longer valid.

![image](https://user-images.githubusercontent.com/1538528/89647578-b944bc00-d8f8-11ea-8fb6-e409ee7894a0.png)

Therefore, this line should be updated:

https://github.com/toddanglin/PublishToDev/blob/e4b0b2a256147209df03ad036c245bac11a1daa4/publishtodev-extension/src/popup.ts#L29

like this:

```javascript
code: `document.querySelector('#article-body').dataset['articleId']`
```
![image](https://user-images.githubusercontent.com/1538528/89647854-3a9c4e80-d8f9-11ea-8415-a71aac67168c.png)

I'm not sure where else I should be looking for.

**Comment by toddanglin** [comment]
Thanks @justinyoo! I merged your PR and published the updated extension to both the Chrome and Edge extension stores. Should be available in the stores after publishing review.
